version: "3.9"

services:
  my_guidelines:
    build: .
    container_nam e: my_guidelines
    ports:
      - "5174:5174" # Porta no host : Porta no container
    environment:
      - PORT=5174 # Porta usada pelo VitePress dentro do container
    volumes:
      - .:/app # Monta o projeto local dentro do container (hot reload)
    command: sh -c "npx vitepress dev docs --host --port 5174"
